### ISSUE TITLE
code convention

### ISSUE THREAD

**Issue by disjukr** [Team-SangSang/sangja#1]
크록포드 아저씨의 컨벤션을 제안해봅니다:
http://javascript.crockford.com/code.html
번역: http://blog.0xabcdef.com/100175347389

꼭 이 컨벤션을 정확하게 지키지는 않더라도(80 column limit을 요즘 시대에 지키는건 좀 과하죠) 인덴트 단위는 탭이나 스페이스 문자 중 하나로 통일하는게 좋을 것 같습니다.

**Comment by qwaz** [comment]
[JS Lint 컨벤션](http://www.jslint.com/lint.html) 사용중입니다.

**Comment by disjukr** [comment]
굳굳
